apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-applicaiton
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wsilverio-dlx/test-repo.git
    targetRevision: HEAD
    path: argo-test

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-applicaiton2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wsilverio-dlx/test-repo.git
    targetRevision: HEAD
    path: argo-test

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true